package = "com.github.nanodeath.typedconfig.test"
class = "GeneratedConfig"
description = "This is the basic configuration file."

[maxLoginTries]
type = "int"
description = "Maximum number of login tries before locking account."
default = 0
checks = ["nonnegative"]

[nameOfTestUser]
type = "str"
checks = ["notblank"]

[timeBetweenFailedLogins]
type = "double"
default = 0.0

[requiredConfig]
type = "str"

[optionalInt]
type = "int"
required = false

[optionalDouble]
type = "double"
required = false

[optionalStr]
type = "str"
required = false

[defaultString]
type = "str"
default = "localhost"

[requiredDuration]
type = "duration"

[defaultDuration]
type = "duration"
default = "100 milliseconds"

[optionalDuration]
type = "duration"
required = false
