package = "com.github.nanodeath.typedconfig.test"
class = "NestedConfig"

[app.port]
type = "int"
default = 8080

[database.port]
type = "int"
default = 5432

[database.credentials.username]
type = "str"
