version: 2.1

orbs:
  codecov: codecov/codecov@3.2.2

jobs:
  build:
    docker:
      - image: gradle:7.4-jdk11
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx2g
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}
      - run: gradle check
      - run:
          name: "Publish to mavenLocal for samples"
          command: gradle publishToMavenLocal
      - run:
          name: "Test sample simple-gradle"
          command: ( cd samples/simple-gradle && gradle run )
      - run:
          name: "Test sample simple-gradle-with-plugin"
          command: ( cd samples/simple-gradle-with-plugin && gradle run )
      - run:
          name: "Test sample simple-gradle-with-plugin-kts"
          command: ( cd samples/simple-gradle-with-plugin-kts && gradle run )
      - run:
          name: "Test sample multi-gradle-with-plugin"
          command: ( cd samples/multi-gradle-with-plugin && gradle run )

      # Codecov
      - run: apt-get update && apt-get install -y gpg
      - codecov/upload
