package = "com.github.nanodeath.typedconfig.test"
class = "GeneratedConfig"

[maxLoginTries]
type = "int"
default = 0
constraints = ["nonnegative"]

[nameOfTestUser]
type = "str"
constraints = ["notblank"]

[timeBetweenFailedLogins]
type = "double"
default = 0.0

[requiredConfig]
type = "str"
