package = "com.github.nanodeath.typedconfig.test"
class = "GeneratedConfig"
description = "This is the basic configuration file."

[maxLoginTries]
type = "int"
description = "Maximum number of login tries before locking account."
default = 0
constraints = ["nonnegative"]

[nameOfTestUser]
type = "str"
constraints = ["notblank"]

[timeBetweenFailedLogins]
type = "double"
default = 0.0

[requiredConfig]
type = "str"
