package = "name.maxaller.konfigurator.test"
class = "GeneratedConfig"

[maxLoginTries]
datatype = "int"
default = 0
constraints = ["nonnegative"]

[nameOfTestUser]
datatype = "str"
constraints = ["notblank"]

[timeBetweenFailedLogins]
datatype = "double"
default = 0.0
