class = "com.github.nanodeath.typedconfig.test.NestedConfig"

[app.port]
type = "int"
default = 8080

[database.port]
type = "int"
default = 5432

[database.credentials.username]
type = "str"

[foo.bar.baz] # don't add any other keys to `foo`!
type = "str"
